# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ZonalStats
                                 A QGIS plugin
 Calculate indices and extract zonal statistics
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-10-11
        copyright            : (C) 2024 by USDA ARS FRR
        email                : kaden.patten@usda.gov
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


import os, platform, subprocess, sys

def plugin_prep():
    
    if platform.system() == "Windows":
        import pip
        installer = "install.bat"
        qgis_py_path = os.path.join(sys.executable.split("bin")[0],"apps\\Python39\\python.exe")
        installer = os.path.join(os.path.dirname(__file__), installer)
        os.chdir(os.path.dirname(__file__))
        print(subprocess.run([installer,qgis_py_path], capture_output=True))
        #print(os.path.join(os.getcwd(),"zsenv\\Lib\\site-packages"))
        #print(os.path.join(os.getcwd(),"requirements.txt"))
        with open('install_err.log','w') as f:
            sys.stderr = f
            pip.main(["install","-t",os.path.join(os.getcwd(),"zsenv\\Lib\\site-packages"),"-r",os.path.join(os.getcwd(),"requirements.txt")])
    if platform.system() == "Linux" or platform.system() == "Darwin":
        installer = "install.sh"
        installer = os.path.join(os.path.dirname(__file__), installer)
        os.chdir(os.path.dirname(__file__))
        print(subprocess.run(["bash",installer], capture_output=True))



# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ZonalStats class from file ZonalStats.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    #print(os.path.join(sys.executable.split("bin")[0],"apps\\Python39\\python3.exe"))
    if not os.path.exists(os.path.join(os.path.dirname(__file__),"zsenv")):
        plugin_prep()

    os.chdir(os.path.dirname(__file__))
    #print(os.getcwd())
    from .zonal_stats import ZonalStats
    return ZonalStats(iface)
