# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ZonalStats
                                 A QGIS plugin
 Calculate indices and extract zonal statistics
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-10-11
        git sha              : $Format:%H$
        copyright            : (C) 2024 by USDA ARS FRR
        email                : kaden.patten@usda.gov
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from qgis.PyQt.QtWidgets import QMessageBox, QLineEdit
import os



class TextInput(QLineEdit):
    def __init__(self, parent):
        super(TextInput, self).__init__(parent)

        #self.setDragEnabled(True)